name: Reusable Terraform Plan

on:
  workflow_call:
    inputs:
      terraform-version:
        type: string

      working-dir:
        type: string

    secrets:
      CLIENT_ID:
        required: true
      SUBSCRIPTION_ID:
        required: true
      TENENT_ID:
        required: true
    outputs:
      plan-exit-code:
        description: "Terraform plan exit code"
        value: ${{ jobs.plan.outputs.exitcode }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.plan.outputs.exitcode }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENENT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Enable Terraform OIDC
        run: echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ${{ inputs.working-dir }}
        run: terraform init

      - name: Terraform Format
        working-directory: ${{ inputs.working-dir }}
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        working-directory: ${{ inputs.working-dir }}
        run: |
          set +e
          terraform plan -detailed-exitcode -out=tfplan
          exitcode=$?
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          [ "$exitcode" -eq 1 ] && exit 1 || true

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ inputs.working-dir }}/tfplan
